"""Generate deterministic, checksum-correct MAC-stream test packets for the FPGA demo."""
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/"tools"))
from packets import make_frame, write_pcap

frames=[make_frame(sequence=1,price=990000),
        make_frame(sequence=2,price=1050000),
        make_frame(sequence=3,price=1110000),
        make_frame(sequence=4,symbol=b"UNKNOWN!"),
        make_frame(sequence=5,port=4321),
        make_frame(sequence=6),make_frame(sequence=7),make_frame(sequence=8)[:65]]
damaged=bytearray(frames[5]); damaged[65]^=1; frames[5]=bytes(damaged)
lines=['`timescale 1ns/1ps','`default_nettype none',
       '// Generated by generate_rom.py. Six normal/error profiles plus MAC error and truncation.',
       'module basys3_packet_rom (input wire [6:0] address, output reg [63:0] data);',
       '    always @* begin','        data = 0;','        case (address)']
for scenario,frame in enumerate(frames):
    for beat,offset in enumerate(range(0,len(frame),8)):
        word=int.from_bytes(frame[offset:offset+8].ljust(8,b'\0'),'little')
        lines.append(f"            7'd{scenario*16+beat}: data = 64'h{word:016x};")
lines+=['            default: data = 0;','        endcase','    end','endmodule','`default_nettype wire','']
(Path(__file__).parent/'basys3_packet_rom.sv').write_text('\n'.join(lines))
write_pcap(Path(__file__).parent/'demo-inputs.pcap',frames)
print('Generated 8 packet profiles / 72 beats. MAC error is a separate final-beat sideband in profile 6.')
